excludes:
  paths:
    - pattern: "*/src/test/**"
      reason: "TEST_OF"
      comment: "This directory is only used for testing and is not part of the released artifacts."
  scopes:
    - pattern: "provided"
      reason: "PROVIDED_DEPENDENCY_OF"
      comment: "Packages provided at runtime by the JDK or container only."
    - name: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."